name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Railway
      uses: railwayapp/railway-action@v2
      with:
        railwayToken: ${{ e55c9eea-f02b-4ff9-aa81-3b6da29ceb1f }}

    - name: Deploy
      run: railway up