name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Railway CLI
      run: npm install -g railway

    - name: Log in to Railway
      run: echo "${{ secrets.RAILWAY_TOKEN }}" | railway login

    - name: Deploy to Railway
      run: railway up